### ISSUE TITLE
Meta issue for Rust API Guidelines

### ISSUE THREAD

**Issue by mcarton** [Manishearth/rust-clippy#1798]
Let's see what makes sense to get into Clippy or not from the [Rust API Guidelines](https://github.com/brson/rust-api-guidelines/blob/master/README.md).

Check the box if a lint or issue already exist for an item.

- **Organization** *(crate is structured in an intelligible way)*
  - [x] Crate root re-exports common functionality ([C-REEXPORT])
    - I don't see how Clippy can know what should be re-exported here.
  - [x] Modules provide a sensible API hierarchy ([C-HIERARCHY])
    - "sensible" is to subjective for Clippy.
- **Naming** *(crate aligns with Rust naming conventions)*
  - [x] Casing conforms to RFC 430 ([C-CASE])
    - This is already covered by `rustc`'s `bad-style` lint group.
  - [ ] Ad-hoc conversions follow `as_`, `to_`, `into_` conventions ([C-CONV])
  - [ ] Methods on collections that produce iterators follow `iter`, `iter_mut`, `into_iter` ([C-ITER])
  - [x] Iterator type names match the methods that produce them ([C-ITER-TY])
    - Issue open: #1789
  - [ ] Ownership suffixes use `_mut` and `_ref` ([C-OWN-SUFFIX])
  - [ ] Single-element containers implement appropriate getters ([C-GETTERS])
- **Interoperability** *(crate interacts nicely with other library functionality)*
  - [ ] Types eagerly implement common traits ([C-COMMON-TRAITS])
    - `Copy`, `Clone`, `Eq`, `PartialEq`, `Ord`, `PartialOrd`, `Hash`, `Debug`,
      `Display`, `Default`
  - [ ] Conversions use the standard traits `From`, `AsRef`, `AsMut` ([C-CONV-TRAITS])
  - [ ] Collections implement `FromIterator` and `Extend` ([C-COLLECT])
  - [ ] Data structures implement Serde's `Serialize`, `Deserialize` ([C-SERDE])
  - [ ] Crate has a `"serde"` cfg option that enables Serde ([C-SERDE-CFG])
  - [ ] Types are `Send` and `Sync` where possible ([C-SEND-SYNC])
  - [ ] Error types are `Send` and `Sync` ([C-SEND-SYNC-ERR])
  - [ ] Error types are meaningful, not `()` ([C-MEANINGFUL-ERR])
  - [ ] Binary number types provide `Hex`, `Octal`, `Binary` formatting ([C-NUM-FMT])
- **Macros** *(crate presents well-behaved macros)*
  - [ ] Input syntax is evocative of the output ([C-EVOCATIVE])
  - [ ] Macros compose well with attributes ([C-MACRO-ATTR])
  - [ ] Item macros work anywhere that items are allowed ([C-ANYWHERE])
  - [ ] Item macros support visibility specifiers ([C-MACRO-VIS])
  - [ ] Type fragments are flexible ([C-MACRO-TY])
- **Documentation** *(crate is abundantly documented)*
  - [ ] Crate level docs are thorough and include examples ([C-CRATE-DOC])
  - [ ] All items have a rustdoc example ([C-EXAMPLE])
  - [ ] Examples use `?`, not `try!`, not `unwrap` ([C-QUESTION-MARK])
  - [x] Function docs include error conditions in "Errors" section ([C-ERROR-DOC])
    - Issue open: #1790
  - [ ] Function docs include panic conditions in "Panics" section ([C-PANIC-DOC])
  - [ ] Prose contains hyperlinks to relevant things ([C-LINK])
  - [ ] Cargo.toml publishes CI badges for tier 1 platforms ([C-CI]) -> #1792
  - [ ] Cargo.toml includes all common metadata ([C-METADATA])
    - authors, description, license, homepage, documentation, repository,
      readme, keywords, categories
  - [x] Crate sets html_root_url attribute "https://docs.rs/$crate/$version" ([C-HTML-ROOT])
    - Issue open: #1788
  - [x] Cargo.toml documentation key points to "https://docs.rs/$crate" ([C-DOCS-RS])
    - Issue open: #1791
- **Predictability** *(crate enables legible code that acts how it looks)*
  - [ ] Smart pointers do not add inherent methods ([C-SMART-PTR])
  - [ ] Conversions live on the most specific type involved ([C-CONV-SPECIFIC])
  - [ ] Functions with a clear receiver are methods ([C-METHOD])
  - [ ] Functions do not take out-parameters ([C-NO-OUT])
  - [ ] Operator overloads are unsurprising ([C-OVERLOAD])
  - [ ] Only smart pointers implement `Deref` and `DerefMut` ([C-DEREF])
  - [ ] `Deref` and `DerefMut` never fail ([C-DEREF-FAIL])
  - [ ] Constructors are static, inherent methods ([C-CTOR])
- **Flexibility** *(crate supports diverse real-world use cases)*
  - [ ] Functions expose intermediate results to avoid duplicate work ([C-INTERMEDIATE])
  - [ ] Caller decides where to copy and place data ([C-CALLER-CONTROL])
  - [x] Functions minimize assumptions about parameters by using generics ([C-GENERIC])
    - Issue open: #1794
  - [ ] Traits are object-safe if they may be useful as a trait object ([C-OBJECT])
- **Type safety** *(crate leverages the type system effectively)*
  - [ ] Newtypes provide static distinctions ([C-NEWTYPE])
  - [ ] Arguments convey meaning through types, not `bool` or `Option` ([C-CUSTOM-TYPE])
  - [x] Types for a set of flags are `bitflags`, not enums ([C-BITFLAG])
    - Issue open: #1795
  - [ ] Builders enable construction of complex values ([C-BUILDER])
- **Dependability** *(crate is unlikely to do the wrong thing)*
  - [ ] Functions validate their arguments ([C-VALIDATE])
  - [ ] Destructors never fail ([C-DTOR-FAIL])
  - [ ] Destructors that may block have alternatives ([C-DTOR-BLOCK])
- **Debuggability** *(crate is conducive to easy debugging)*
  - [x] All public types implement `Debug` ([C-DEBUG])
    - Issue open: #1796

  - [ ] `Debug` representation is never empty ([C-DEBUG-NONEMPTY])
- **Future proofing** *(crate is free to improve without breaking users' code)*
  - [ ] Structs have private fields ([C-STRUCT-PRIVATE])
  - [ ] Newtypes encapsulate implementation details ([C-NEWTYPE-HIDE])
- **Necessities** *(to whom they matter, they really matter)*
  - [x] Public dependencies of a stable crate are stable ([C-STABLE])
    - Issue open: #1797
  - [ ] Crate and its dependencies have a permissive license ([C-PERMISSIVE])

**Comment by kennytm** [comment]
C-PANIC-DOC  should point to #1791, C-DOCS-RS should point to #1788 or a new issue.

**Comment by killercup** [comment]
Nice work!

<small>(You should use URLs with the commit hash in them (press <kbd>y</kbd> on github.com) so they continue to work in the future.)</small>

**Comment by mcarton** [comment]
Thanks! I volontarily did not do that for this so that we point to the latest version of the guidelines. This might mean that we get broken links once in a while but that'll mean that the list here is outdated.

**Comment by clarcharr** [comment]
Note that C-EXAMPLE is covered by #1454.

**Comment by mcarton** [comment]
Not quite, `C-EXAMPLE` is about not having an example, #1454 is about having a non-relevant example.

**Comment by killercup** [comment]
As [predicted](https://github.com/rust-lang-nursery/rust-clippy/issues/1798#issuecomment-304639343), the links no longer work. Now, how using [links like this one](https://github.com/rust-lang-nursery/api-guidelines/blob/e8ca2598f15a48928de2781759c1994e04fb1a0f/src/flexibility.md#functions-minimize-assumptions-about-parameters-by-using-generics-c-generic) instead?

**Comment by Susurrus** [comment]
> Types eagerly implement common traits (C-COMMON-TRAITS)

`rustc` has `missing-copy-implementations` for `Copy` and `missing-debug-implementations` for `Debug`, but I don't see anything in `rustc` or `clippy` for any of the other traits:
 * `Clone`
 * `Eq`
 * `Ord`
 * `PartialOrd`
 * `Hash`
 * `Display`
 * `Default`

This was checked off in the original checklist, so I wanted to double-check I wasn't missing anything.

**Comment by philipcraig** [comment]
In the C-CONV-TRAITS subsection in this issue, could @mcarton please explicitly  add a bullet "``Into`` and ``TryInto`` are never implemented"?
